# Generated by Django 3.2.19 on 2023-05-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='suject',
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
